services:
    mysql:
        image: mysql:8.4
        restart: always
        container_name: smartedu
        environment: 
            - MYSQL_DATABASE=smartedu
            - MYSQL_ROOT_PASSWORD=docker
        ports: 
            - '3306:3306'
        networks:
            - smartedu-network
networks:
    smartedu-network:
        driver: bridge